import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

function getOpenAI() {
  return new OpenAI({
    baseURL: "https://api.deepseek.com/v1",
    apiKey: process.env.OPENAI_API_KEY,
  });
}

export async function POST(req: NextRequest) {
  try {
    const { topic, numCards, contentType, subject } = await req.json();

    const prompt = `You are an expert educator specializing in memory techniques and spaced repetition. Generate a flashcard deck for the following:

**Deck Details:**
- Topic: ${topic}
- Subject: ${subject || "General"}
- Number of Cards: ${numCards}
- Content Type: ${contentType}

Content types to generate based on "${contentType}":
- Term/Definition: Key terms with definitions
- Formula/Equation: Scientific or mathematical formulas with explanations
- Concept/Explanation: Abstract concepts with detailed explanations
- Mixed: Combination of all types

Please generate the following spaced repetition deck:

# SPACED REPETITION FLASHCARD DECK
## ${topic} | ${subject || "General"} | ${numCards} Cards

---

# 📚 FLASHCARD SCHEDULE OVERVIEW

Using the SM-2 spaced repetition algorithm, here is your recommended review schedule:

| Review | Interval | Days from Start |
|--------|----------|-----------------|
| Initial Learn | Day 0 | Today |
| First Review | +1 day | Day 1 |
| Second Review | +3 days | Day 4 |
| Third Review | +7 days | Day 8 |
| Fourth Review | +14 days | Day 15 |
| Fifth Review | +30 days | Day 30 |
| Sixth Review | +60 days | Day 60 |

*Adjust intervals based on your personal retention. If a card is difficult, repeat the same interval.*

---

# FLASHCARD DECK

## Card 1
**Type:** ${contentType.includes("Term") ? "Term/Definition" : contentType.includes("Formula") ? "Formula" : contentType.includes("Concept") ? "Concept" : "Mixed"}
**Tags:** #${topic.replace(/\s+/g, "-")} #${subject?.replace(/\s+/g, "-") || "general"}

**FRONT:**
[Key term / concept / formula]

**BACK:**
[Clear definition, explanation, or breakdown]

**Memory Tip:**
[Mnemonic, analogy, or memory palace suggestion]

**Interval (SM-2):** Initial: 1 day → If recalled easily: 3 days → 7 days → 14 days → 30 days

---

[Continue for all ${numCards} cards...]

[Generate ${numCards} unique flashcards, each with:]
- Unique front content relevant to the topic
- Clear, comprehensive back
- A specific memory tip, mnemonic, or study technique
- Spaced repetition interval guidance
- Relevant hashtags for organization

---

# 📋 STUDY TIPS BY CARD

| Card # | Topic Focus | Best Study Technique |
|--------|-------------|----------------------|
${Array.from({length: Math.min(Number(numCards), 10)}, (_, i) => `| ${i+1} | [Sub-topic ${i+1}] | Active recall + spaced repetition |`).join("\n")}

---

# 📊 DECK STATISTICS
- Total Cards: ${numCards}
- Content Type: ${contentType}
- Subject: ${subject || "General"}
- Estimated Study Time: ${Math.ceil(Number(numCards) * 2)} minutes per session
- Review Schedule: SM-2 Algorithm (see above)
- Export Format: Plain text (Anki, Quizlet compatible)

---

# HOW TO USE THIS DECK

**Recommended Apps for Import:**
1. **Anki** — Free, cross-platform, SM-2 algorithm
2. **Quizlet** — Cloud sync, game modes
3. **RemNote** — Zettelkasten + spaced repetition
4. **Obsidian + Spaced Repetition Plugin** — For knowledge workers

**Import Instructions:**
Copy the card content (Front | Back format) into your preferred app and set the review schedule to SM-2 or use the intervals listed above.

---

# BONUS: mnemonics & memory palace anchors

For each major concept group, provide:
1. A mnemonic phrase or acronym
2. A physical location (if using memory palace method)
3. A visualization tip

---
*Generated by AI Flashcard Generator — Review and customize before studying.*`;

    const openai = getOpenAI();
    const completion = await openai.chat.completions.create({
      model: "deepseek-chat",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
      max_tokens: 4500,
    });

    const content = completion.choices[0]?.message?.content || "No response generated.";
    return NextResponse.json({ result: content });
  } catch (error: unknown) {
    console.error("Error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
